services:
  postgres:
    image: postgres:16
    container_name: aurapark-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aurapark
      POSTGRES_USER: aurapark
      POSTGRES_PASSWORD: aurapark123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
